apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
type: Opaque
stringData:
  DB_PASSWORD: "admin123"
  JWT_SECRET: "dev-portfolio-jwt-secret-change-in-real-deployment-min-32"
  DATABASE_URL: "postgresql://postgres:admin123@postgres-service:5432/stockflow_db?schema=public"